// Generated by https://quicktype.io

export interface AllHeroesInterface {
  Status: string;
  foundHeroes: FoundHero[];
}

export interface FoundHero {
  superhero: string;
  publisher: string;
  alterEgo: string;
  firstAppearance: string;
  characters: string;
  photo: string;
  userId: string;
  __v: number;
  id: string;
}
