// Generated by https://quicktype.io

export interface GetHeroResInterface {
  status: string;
  userFound: UserFound;
}

export interface UserFound {
  superhero: string;
  publisher: string;
  alterEgo: string;
  firstAppearance: string;
  characters: string;
  photo: string;
  userId: string;
  __v: number;
  id: string;
}
