// Generated by https://quicktype.io

export interface HeroRes {
  Status: string;
  savedHero: SavedHero;
}

export interface SavedHero {
  superhero: string;
  publisher: string;
  alterEgo: string;
  firstAppearance: string;
  characters: string;
  photo: string;
  userId: string;
  __v: number;
  id: string;
}
