// Generated by https://quicktype.io

export interface UdateHeroResInterface {
  status: string;
  updatedHero: UpdatedHero;
}

export interface UpdatedHero {
  superhero: string;
  publisher: string;
  alterEgo: string;
  firstAppearance: string;
  characters: string;
  photo: string;
  userId: string;
  __v: number;
  id: string;
}
